sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KTu68wwqDeULkDOh5za5dUnqppHQnKNcDbXTsYfLr9og5KEQqpYCcQm7FMv7UjJKxxRxH3Wzdq2wykTkjPf2TU+KgtJ8TCKroAz/O3g0kd44ghQHyx1hCJDwVQOAHpgkbhewO8xNmD8n66Iy9htBP0mT7ftJBVSjzA+a60PPuoCFzFt3KyFVrz1YqS3F08ioM6JNmpAxj5GFkCMs+lrzcR+IQx55NR8a0rP74yOJsu91e9BNVTUcJhGxLQImxlYnESiw8H4PijtxzDf3n+BrXdx8AESdTsbT7tGmbfvGoY6Ew7x5cjldPfH5ETR4xJSwUltLMuLrg4nEZNvutrjj/Y/txqDo5yVyQkiFxefQAZqdDeh6rd1ATHVeDycOFxECJlvngEVXbI++c0L6asvNB2PVstOSieCEDh261gg5Ic2JgGFpYPlkUgzbRaiHqCP923ufy8T+IMRwUv0KkanrtOIbbSxC4m/HhzsL/sZb4Y9jTxKbVakg9U3VvuVoWgNl4FYjbp+XD7uX63kw8eqEMeQId7L5s8rV3lICvdQtDt48QT50Lm1iLdlBc3xIzUJqx1oEKppOcUFOwJOCjgBmDudXNvJ5JNBHlLFgytd45L0xLtifej9rfz04NLxKUoGmtbsKDroWJ8umqdTjfZhaZZjxwTnJQOk2CF4ry0QFSUo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Conquest-of-the-Old-Southwest--the-romantic-story-of-the-early-pioneers-into-Virginia-the-__2390
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy